### ISSUE TITLE
Problem when playing two instances

### ISSUE THREAD

**Issue by qarlosh** [MightyPrinny/godot-FLMusicLib#1] opened 2019-11-29 19:35 UTC
I have two instances (both created with `FLMusicLib.new()`) because I want to use one for music and the other for sfx. At first, one instance starts playing music, but if the second instance plays a sound (it is just a short track), when this ends, both instances stop playing.

I am using Godot 3.2beta1. Both instances are playing nsf files.

**Comment by MightyPrinny** [comment] 2019-12-01 01:56
It probably crashes, I'll look into it tomorrow, but keep in mind that emulation is used for each instance that uses formats supported by GameMusicEmu, having a lot of them for sound effects might have a performance impact depending on how many instances you make and your machine and with one instance only one sound effect can play at a time, I would recommend using wav files for sound effects.

**Comment by qarlosh** [comment] 2019-12-01 15:08
Thank you for your response and advice. I want to keep it (relatively) true to old games, so I did think to have two instances, one for music and one for sfx, like some old arcade machines. I have made a simple manager for sounds, playing only one at once, assigning priorities, and it works fine. If performance suffers, then maybe I will render the sounds to wavs, but keeping the "only one sound at once" restriction

**Comment by MightyPrinny** [comment] 2019-12-01 18:05
could you upload a project that has everything I need to test this? I can't reproduce it

**Comment by MightyPrinny** [comment] 2019-12-01 18:07
never mind I started playing random sfx and music stopped

**Comment by MightyPrinny** [comment] 2019-12-01 20:56
It should be fixed now, I'll make new binaries soon.

**Closed as completed by MightyPrinny** 2019-12-01 20:56 UTC
Labels: bug

**Comment by qarlosh** [comment] 2019-12-01 21:07
Thanks, I'll check when binaries are ready

btw, this is a great addon!

**Comment by qarlosh** [comment] 2019-12-03 17:25
Just tested the 0.5.1 binaries, working great now :+1:
